title: Senai Kalafat - Software Developer
description: > # this means to ignore newlines until "baseurl:"
  Küçük notlar, faydalı bilgiler, teknik tavsiyeler, yazılım mimarisi konuları, üretkenlik vb üzerine paylaştığım mikro blog - Senai Kalafat
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://www.senaikalafat.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Senai Kalafat # add your name
author-img: profil.jpeg # add your photo
about-author: Bilgisayar Mühendisliği Mezunu, Yazılım Mühendisi, Meraklı, İşini Seven # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: #soptimizer # add your Github handle
social-linkedin: #senai-kalafat # add your Linkedin handle
social-email: #senaikalafat@gmail.com # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: G-7VRNKH3WBN

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
